# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Year', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='films',
            name='Genres',
            field=models.ManyToManyField(related_name='Films', to='movie.Genres'),
        ),
        migrations.AddField(
            model_name='actor',
            name='Films',
            field=models.ManyToManyField(related_name='Actor', to='movie.Films'),
        ),
    ]
