# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='Genres',
            new_name='Type',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='Films',
        ),
        migrations.AddField(
            model_name='films',
            name='Actor',
            field=models.ManyToManyField(related_name='Films', to='movie.Actor'),
        ),
    ]
